/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            pong?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/otp/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Send a new OTP or resend existing OTP if within resend window */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Request to send an OTP to the user's email address */
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Email
                         * Format: email
                         * @description Email address
                         * @default test@example.com
                         */
                        email: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @default true
                             * @enum {boolean}
                             */
                            success: true;
                            /** @default OTP sent successfully */
                            message: string;
                            /**
                             * Format: uuid
                             * @default 0d518202-dd66-4b75-b1c9-d31937d473d6
                             */
                            correlationId: string;
                        };
                    };
                };
                /** @description Error response for send/resend/verify OTP */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @default false
                             * @enum {boolean}
                             */
                            success: false;
                            /** @default Please enter a valid email address */
                            message: string;
                            /**
                             * @default [
                             *       {
                             *         "code": "invalid_email",
                             *         "path": [
                             *           "email"
                             *         ],
                             *         "message": "Invalid email format"
                             *       }
                             *     ]
                             */
                            errors: {
                                /** @default invalid_string */
                                code: string;
                                /**
                                 * @default [
                                 *       "email"
                                 *     ]
                                 */
                                path: string[];
                                /** @default Please enter a valid email address */
                                message: string;
                            }[];
                            /**
                             * Format: uuid
                             * @default 5351c05a-923a-4354-b85c-dc57a5d30c27
                             */
                            correlationId: string;
                        };
                    };
                };
                /** @description Rate limit response */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @default false
                             * @enum {boolean}
                             */
                            success: false;
                            /** @default Rate limit exceeded */
                            message: string;
                            /**
                             * Format: uuid
                             * @default dae5a8ca-f7f5-48e7-8954-33f79ceb66a1
                             */
                            correlationId: string;
                        };
                    };
                };
                /** @description Error response for send/resend/verify OTP */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @default false
                             * @enum {boolean}
                             */
                            success: false;
                            /** @default Please enter a valid email address */
                            message: string;
                            /**
                             * @default [
                             *       {
                             *         "code": "invalid_email",
                             *         "path": [
                             *           "email"
                             *         ],
                             *         "message": "Invalid email format"
                             *       }
                             *     ]
                             */
                            errors: {
                                /** @default invalid_string */
                                code: string;
                                /**
                                 * @default [
                                 *       "email"
                                 *     ]
                                 */
                                path: string[];
                                /** @default Please enter a valid email address */
                                message: string;
                            }[];
                            /**
                             * Format: uuid
                             * @default 5351c05a-923a-4354-b85c-dc57a5d30c27
                             */
                            correlationId: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/otp/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Resend an existing OTP if within resend window */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Request to resend an OTP to the user's email address */
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Email
                         * Format: email
                         * @description Email address
                         * @default test@example.com
                         */
                        email: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @default true
                             * @enum {boolean}
                             */
                            success: true;
                            /** @default OTP sent successfully */
                            message: string;
                            /**
                             * Format: uuid
                             * @default 0d518202-dd66-4b75-b1c9-d31937d473d6
                             */
                            correlationId: string;
                        };
                    };
                };
                /** @description Error response for send/resend/verify OTP */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @default false
                             * @enum {boolean}
                             */
                            success: false;
                            /** @default Please enter a valid email address */
                            message: string;
                            /**
                             * @default [
                             *       {
                             *         "code": "invalid_email",
                             *         "path": [
                             *           "email"
                             *         ],
                             *         "message": "Invalid email format"
                             *       }
                             *     ]
                             */
                            errors: {
                                /** @default invalid_string */
                                code: string;
                                /**
                                 * @default [
                                 *       "email"
                                 *     ]
                                 */
                                path: string[];
                                /** @default Please enter a valid email address */
                                message: string;
                            }[];
                            /**
                             * Format: uuid
                             * @default 5351c05a-923a-4354-b85c-dc57a5d30c27
                             */
                            correlationId: string;
                        };
                    };
                };
                /** @description Error response for send/resend/verify OTP */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @default false
                             * @enum {boolean}
                             */
                            success: false;
                            /** @default Please enter a valid email address */
                            message: string;
                            /**
                             * @default [
                             *       {
                             *         "code": "invalid_email",
                             *         "path": [
                             *           "email"
                             *         ],
                             *         "message": "Invalid email format"
                             *       }
                             *     ]
                             */
                            errors: {
                                /** @default invalid_string */
                                code: string;
                                /**
                                 * @default [
                                 *       "email"
                                 *     ]
                                 */
                                path: string[];
                                /** @default Please enter a valid email address */
                                message: string;
                            }[];
                            /**
                             * Format: uuid
                             * @default 5351c05a-923a-4354-b85c-dc57a5d30c27
                             */
                            correlationId: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Verify an OTP code */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Request to verify an OTP */
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Email
                         * Format: email
                         * @description Email address
                         * @default test@example.com
                         */
                        email: string;
                        /**
                         * OTP
                         * @description OTP code
                         * @default 123456
                         */
                        otp: string;
                    };
                };
            };
            responses: {
                /** @description Success response for verify OTP */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @default true
                             * @enum {boolean}
                             */
                            success: true;
                            /**
                             * @default true
                             * @enum {boolean}
                             */
                            valid: true;
                            /** @default OTP verified successfully */
                            message: string;
                            /**
                             * Format: uuid
                             * @default bc1defee-8f94-4d1c-89c0-c946f79364d0
                             */
                            correlationId: string;
                        };
                    };
                };
                /** @description Error response for send/resend/verify OTP */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @default false
                             * @enum {boolean}
                             */
                            success: false;
                            /** @default Please enter a valid email address */
                            message: string;
                            /**
                             * @default [
                             *       {
                             *         "code": "invalid_email",
                             *         "path": [
                             *           "email"
                             *         ],
                             *         "message": "Invalid email format"
                             *       }
                             *     ]
                             */
                            errors: {
                                /** @default invalid_string */
                                code: string;
                                /**
                                 * @default [
                                 *       "email"
                                 *     ]
                                 */
                                path: string[];
                                /** @default Please enter a valid email address */
                                message: string;
                            }[];
                            /**
                             * Format: uuid
                             * @default 5351c05a-923a-4354-b85c-dc57a5d30c27
                             */
                            correlationId: string;
                        };
                    };
                };
                /** @description Error response for send/resend/verify OTP */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @default false
                             * @enum {boolean}
                             */
                            success: false;
                            /** @default Please enter a valid email address */
                            message: string;
                            /**
                             * @default [
                             *       {
                             *         "code": "invalid_email",
                             *         "path": [
                             *           "email"
                             *         ],
                             *         "message": "Invalid email format"
                             *       }
                             *     ]
                             */
                            errors: {
                                /** @default invalid_string */
                                code: string;
                                /**
                                 * @default [
                                 *       "email"
                                 *     ]
                                 */
                                path: string[];
                                /** @default Please enter a valid email address */
                                message: string;
                            }[];
                            /**
                             * Format: uuid
                             * @default 5351c05a-923a-4354-b85c-dc57a5d30c27
                             */
                            correlationId: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/error-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Log an error for debugging and production support */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        correlationId: string;
                        /** Format: email */
                        email?: string;
                        errorMessage: string;
                        errorType?: string;
                        errorStack?: string;
                        requestPath?: string;
                        requestMethod?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            message?: string;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
